# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Xianglong Xu
# title: Currently Pursuing MSIS at the Pitt
email: sean652039@gmail.com
# email_title: Email (Email title override)
phone: +1 412-452-5278
# phone_title: Phone (Phone title override)
website: https://github.com/Sean652039
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  Sean652039
#stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: xianglongxu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.PNG
about_content: | # this will include new lines to allow paragraphs
    ðŸ‘‹ Hi there! I'm **Xianglong Xu**, currently pursuing a Master's degree in Information Science at the University of Pittsburgh, with a focus on AI. My academic journey began at North China Electric Power University, where I earned a Bachelor's degree in Computer Science - Specialization in AI.

    ðŸ§  My expertise lies in several machine learning algorithms, and I'm proficient in programming languages such as Python and R. I thrive on collaboration and am known for being outgoing. Fluent in English (with a score of 8 in IELTS Speaking), I easily connect with people from diverse cultures, fostering open communication and effective teamwork.

    âš½ Outside the world of tech, I'm passionate about soccer. Beyond the excitement it brings, soccer has instilled in me a spirit of perseverance and resilience.

    ðŸŒ I'm always open to connecting with like-minded professionals, discussing AI, or exploring potential collaborations. Feel free to reach out to me via email at xix110@pitt.edu or Sean65039@gmail.com. You can also connect with me directly on LinkedIn.
   

content:
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: University of Pittsburgh
        sub_title: MS in Information Science 
        caption: August 2023 â€“ May 2025
        quote: >
          (GPA: 3.95/4.0)
        description: | # this will include new lines to allow paragraphs
          My studies at the University of Pittsburgh not only expanded my knowledge but, more importantly, the diverse cultural environment enriched my perspectives, providing insights that extend beyond the confines of textbooks. Interacting with individuals from various cultural backgrounds not only allowed me to approach AI from different angles but also enhanced my collaborative skills. This multicultural exposure has been instrumental in shaping my holistic understanding of artificial intelligence.
      - layout: top-left
        title: North China Electric Power University
        sub_title: BS in Computer Science - Specialization in AI 
        caption: September 2019 â€“ June 2023
        quote: >
          (GPA: 3.59/4.0)
        description: | # this will include new lines to allow paragraphs
          During my four years at North China Electric Power University, Intelligent Science and Technology, synonymous with the field of AI, became the focal point of my academic pursuits. Over this period, I not only acquired a profound understanding of crucial machine learning algorithms but also delved into the underlying mathematical principles, encompassing probability theory, linear algebra, and optimization theory.
          This undergraduate journey not only laid a robust foundation for my subsequent pursuit of advanced studies in artificial intelligence but also honed my coding skills.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Vosyn Inc.
        sub_title: AI Software Developer Intern
        caption: May 2024 â€“ August 2024, Chicago, Illinois(Remote)
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Designed and implemented an end-to-end Python-based Speaker Diarization System to gradually replace the pyannote library due to its long runtime, enabling faster identification of multiple speakersâ€™ timelines in audio.
          - Implemented a Chinese Restaurant Process-based approach in the clustering, achieving 10x faster execution time than pyannote, and trained a Speaker Change Detection model, enabling more accurate speaker timelines.
          - Integrated WebRTCâ€™s Voice Activity Detection with a ring buffer to reduce detection errors by considering contextual frames and employed temporary files with io.BytesIO for large audio files to minimize memory usage.
          - Developed evaluation using the AMI Meeting Corpus datasets to calculate Diarization Error Rate, providing a metric for developers to assess the improvements made to the system, enabling continuous optimization.
      - layout: left
        title: Yunnan Gold Mining Group Co. LTD.
        sub_title: Information Engineer Intern
        caption: February 2022, August 2022, Kunming, Yunnan(Onsite)
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Implemented a Flask and SQLite-based employee data management web application for internal HR operations.
          - Designed relational tables to meet HR requirements by establishing relationships among employees, departments, and positions, minimizing redundancy and accommodating future needs without altering core structures.
          - Created a visualizations dashboard leveraging Chart.js, allowing users to view real-time data, including the number of employees in each department and position distribution, with detailed information displayed on hover.
        
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Music Generation with Deep Learning
        # link: https://github.com/Sean652039/NLP_Classification
        # link_text: GitHub
        additional_links:
          - title:  GitHub
            icon: fab fa-github
            url: https://github.com/Sean652039/Diffusion_Model_for_Generating_Music
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          September 2024 â€“ December 2024
        description: | # this will include new lines to allow paragraphs
          - Designed and implemented a dual-model music generation system that leverages Stable Diffusion and Restricted Boltzmann Machines for generating roll plots from music MIDI files, which are then converted to MIDI files.
          - Preprocessed plots for training by truncating the x-axis representing time, expanding the y-axis (music pitch range) by replicating pitch rows to match input dimensions, and applying color-coding to increase dimensions.
          - Designed a Stable Diffusion training pipeline using a UNet2DModel with adaptive pixel-wise weighted loss, dynamic noise scheduling, and checkpoint management, with architecture aligned to the preprocessing of plots.
          - Designed an RBM for denoising, treating each pixel as a visible node with a hidden layer of half the visible nodes, while incorporating adaptive noise generation, multi-type noise injection, and contrastive divergence training.
          - Engineered an image-to-MIDI conversion pipeline that transforms generated plots into binary representations through adaptive thresholding, translating pixel data into MIDI note sequences with time and pitch mapping.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: AI Snake
        # link: https://github.com/Sean652039/NLP_Classification
        # link_text: GitHub
        additional_links:
          - title:  GitHub
            icon: fab fa-github
            url: https://github.com/Sean652039/snake-ai
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          March 2024 â€“ May 2024
        description: | # this will include new lines to allow paragraphs
          - Optimized a reinforcement learning AI agent for the â€™Snakeâ€™ game using Proximal Policy Optimization with MLP and CNN architectures, enhancing the reward-punishment mechanism and achieving a 5% score improvement.
          - Engineered a Markov chain model to analyze the game process by treating each time step as a Markov state, suggesting that compressing the snakeâ€™s body to reduce the space it occupies is one potential optimization.
          - Developed a recursive territory calculation algorithm inspired by Go game rules to compute the empty cells enclosed by the snakeâ€™s body, using the number of enclosed cells as a penalty criterion to train the agent.
      # - layout: left
      #   border: weak  # Value of `weak` will display a weak border below this item. # Any 
      #                 # other value (or no value) means no border will be displayed
      #   title: LSTM-based text classification
      #   # link: https://github.com/Sean652039/NLP_Classification
      #   # link_text: GitHub
      #   additional_links:
      #     - title:  GitHub
      #       icon: fab fa-github
      #       url: https://github.com/Sean652039/NLP_Classification
      #   #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #   #     icon: fab fa-github
      #   #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #   quote: >
      #     December 2023 â€“ January 2024
      #   description: | # this will include new lines to allow paragraphs
      #     - Utilizing jieba segmentation and part-of-speech tagging for text processing. Accomplished data preprocessing and sequence conversion.
      #     - Constructing a vocabulary using a statistical word frequency approach. Incorporating stop-word filtering to enhance the model's robustness.
      #     - Implemented a text classification model using PyTorch, inheriting from the nn.Module class. The model incorporates an embedding layer (nn.Embedding), an LSTM layer (nn.LSTM), and a fully connected layer (nn.Linear). To prevent overfitting, a Dropout layer (nn.Dropout) is included. The model processes input sequences through forward propagation (forward method) to produce classification predictions.
      #     - Trained using Tencent AI Lab's word embeddings, the model achieves a test set accuracy exceeding 95%.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Data Analysis for PPG Industries, Inc (ppg.com)
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          November 2023 â€“ December 2023
        description: | # this will include new lines to allow paragraphs
          - Employed ggplot for crafting insightful visualizations to elucidate complex relationships and input distributions.
          - Utilized the lm() function for MLE modeling and rstanarm's stan_lm() for Bayesian modeling in both regression and classification tasks. Applied the glmet package to fit models with Lasso regularization techniques, enhancing robustness. Leveraged the caret package for training a variety of machine learning models, including Random Forest, Neural Network, SVM, and XGBoost, with a focus on model tuning for optimal performance.
          - Employed a meticulous evaluation of diverse metrics to discern and select the best-performing models for both regression and classification tasks.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Implication of Password Management Systems
        link: https://sean652039.github.io/Pitt_HIP_Passwords.io/
        link_text: Demonstration of the project
        additional_links:
          # - title:  Page for project 
          #   icon: fab fa-github
          #   url: https://sean652039.github.io/Pitt_HIP_Passwords.io/
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          November 2023 â€“ December 2023
        description: | # this will include new lines to allow paragraphs
          - Implemented a novel approach inspired by the "Google Effect" on memory to address potential challenges in emergency password recall within password management systems.
          - Introduced a segmented password system, compelling users to input randomly selected segments during login, effectively boosting engagement and facilitating improved recall, especially in emergency scenarios.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: YOLO-Based Vehicle Detection
        link: https://blog.csdn.net/qq_46684105/article/details/132132725?spm=1001.2014.3001.5501
        link_text: Solved Issues (CN)
        additional_links:
          # - title:  
          #   icon: 
          #   url: 
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          March 2023 â€“ June 2023
        description: | # this will include new lines to allow paragraphs
          - Proposed a YOLOv7-based model for vehicle detection, trained & validated with UA-DETRAC dataset.
          - Adopted a frame sampling strategy (2 frames for training, 10 frames for validation) to mitigate overfitting risks in a 25 fps video dataset. Innovatively included random test set folders in training to improve model adaptability and handle distribution differences.
          - Successfully deployed the optimized model on Android, utilizing the NCNN open-source framework from GitHub. This ensures efficient and resource-friendly execution on mobile devices.
      # - layout: left
      #   border: weak  # Value of `weak` will display a weak border below this item. # Any 
      #                 # other value (or no value) means no border will be displayed
      #   title: The Influence of Dominant Response on Non-dominant Response (The Stroop Effect)
      #   link: https://github.com/Sean652039/Stroop
      #   link_text: GitHub
      #   additional_links:
      #     - title:  GitHub
      #       icon: fab fa-github
      #       url: https://github.com/Sean652039/Stroop
      #   #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #   #     icon: fab fa-github
      #   #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #   quote: >
      #     04/2021â€”05/2021
      #   description: | # this will include new lines to allow paragraphs
      #     - Study the Stroop effect, focusing on non-dominant vs. dominant responses' impact.
      #     - Adapted Python's `Pygame` library for visualizing word colors and developed the experimental platform.
      #     - Optimized code, reducing run time and improving code structure.     
  - title: Resume
    layout: list
    content: 
      - layout: text
        title: Download Resume   
        link: https://github.com/Sean652039/Sean652039.github.io/raw/master/images/Xianglong_Xu_Resume.pdf 
        link_text: Click to Download Resume 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Apart from studying, my greatest passion lies in exploring the unknown. I love delving into diverse cultures, aspiring to travel far and wide, and engage as much as possible with the local communities. Along the way, I also indulge in photography, using the language of the lens to articulate my understanding of the world.
      # The statue of liberty
      ![](/images/NY.jpg "New York")
      # Quebec City
      ![](/images/Quebec.jpg "Quebec")
      # Jackson Hole
      ![](/images/Jackson.jpeg "Jackson Hole")


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
